### ISSUE TITLE
The type errors in the PDF417BarcodeComponent

### ISSUE THREAD

**Issue by PatrickLh** [ansemjo/angular2-pdf417-barcode#3]
Hi, 
I found there lose the type define for the @ViewChild('container') container in the PDF417BarcodeComponent , it will cause error when compiler .

**Comment by ansemjo** [comment]
I haven't been using this module for a long time and haven't successfully used the compiler in any of my projects yet but I'd be happy to accept a pull request with a fix!

Any specific errors would greatly help aswell.

**Comment by ansemjo** [comment]
I've updated the package due to another issue (#5) and repackaged it for Angular 6+. Please re-check if it still throws any type errors?

**Comment by ansemjo** [comment]
I'll assume this is fixed?
