### ISSUE TITLE
Support for Angular 7+?

### ISSUE THREAD

**Issue by bonjourclaudio** [ansemjo/angular2-pdf417-barcode#5]
Will this package be updated for Angular 7+ soon?

Thanks!

**Comment by ansemjo** [comment]
I created a new scaffolding with the `ng` cli and converted the old package. It is now published as [pdf417-barcode](https://www.npmjs.com/package/pdf417-barcode) on npm with updated instructions aswell.

In my tests it should be compatible with Angular 6 and upwards now.

Please get back to me if it doesn't work.

**Comment by bonjourclaudio** [comment]
Thank you so much! Works perfectly fine 😸
